- project:
    templates:
      - openstack-lower-constraints-jobs-horizon
      - check-requirements
      - horizon-nodejs10-jobs
      - openstack-python-jobs-horizon
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-py36:
            voting: false
            required-projects:
              - openstack/horizon
        - horizon-openstack-tox-python3-django111
    gate:
      jobs:
        - horizon-openstack-tox-python3-django111
