- project:
    templates:
      - openstack-lower-constraints-jobs-horizon
      - check-requirements
      - horizon-non-primary-django-jobs
      - horizon-nodejs10-jobs
      - openstack-python3-wallaby-jobs-horizon
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
